version: 1.0.{build}
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
image:
- Visual Studio 2017
build:
  publish_nuget: true
  verbosity: minimal
install:
- cmd: "type c:\\windows\\system32\\drivers\\etc\\hosts\n\nping api.nuget.org\ndotnet restore"
on_success:
- curl -s -o copilot https://copilot.blackducksoftware.com/ci/appveyor/scripts/upload
- bash copilot
nuget:
  account_feed: true
  project_feed: true

